# Generated by Django 4.2.4 on 2023-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0006_kurs_is_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='resim',
            field=models.FileField(blank=True, upload_to='kurs/', verbose_name='Kurs Resmi'),
        ),
    ]
